controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::index

omdb_search:
    path: /omdb
    controller: App\Controller\OmdbController::searchOmdb